spring:
  datasource:
    url: jdbc:mysql://localhost:3306/english_learning_system?allowMultiQueries=true&serverTimezone=GMT-8&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name:  com.mysql.cj.jdbc.Driver

  mvc:
    #配置它以后移动html页面就不用改路径了！
    static-path-pattern: /static/**    #静态资源的请求方式
    pathmatch:
      matching-strategy: ant_path_matcher  # 解决Swagger 3.0.0与Spring Boot 2.6.x以上版本的兼容问题
  resources:
    static-locations: classpath:/static/  # 静态资源的配置位置，可以写成一个数组配置多个目录

  mail:
    host: smtp.qq.com
    username: xxxxx@qq.com  # 邮箱地址
    password: xxxxxxx # 授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true



  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.chun.myspringboot.pojo
  configuration:
    map-underscore-to-camel-case: on #采用驼峰标识


# pagehelper分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# DeepSeek API配置（用于聊天功能）
deepseek:
  api:
    key: sk-031181b730b04d3cb3f563c9e5d0aaa1  # 替换为您的DeepSeek API密钥
    url: https://api.deepseek.com/v1/chat/completions
    model: deepseek-chat  # DeepSeek聊天模型ID

# 硅基流动API配置（用于图像生成）
siliconflow:
  api:
    key: sk-iqbpulsbsuoabenegffgihafnhuvmzapeempkmzsggxwdlac  # 替换为您的硅基流动API密钥
    url: https://api.siliconflow.cn/v1/images/generations  # 图像生成API URL
    model: black-forest-labs/FLUX.1-schnell  # 图像生成模型ID

# JWT配置
jwt:
  secret: EnglishLearningSystemSecretKey  # JWT密钥
  expiration: 86400  # Token有效期（秒），默认24小时
  tokenPrefix: Bearer  # Token前缀
  header: Authorization  # 存放Token的Header Key

# Swagger配置
springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs  # Swagger API文档路径
